<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use Cadastro\Model;
use Faker\Generator as Faker;

$factory->define(\Cadastro\Models\CadastroEscolas::class, function (Faker $faker) {
    return [
        'CGC_Escola' => $faker->cnpj,
        'CGC_Mantenedora' => $faker->cnpj,
        'Razao_Social' => $faker->company,
        'Nome_Fantasia' => $faker->companySuffix,
        'Endereco' => $faker->streetName,
        'Numero' => $faker->randomDigit,
        'Complemento' => $faker->word,
        'Bairro' => $faker->word,
        'Cidade' => $faker->cityPrefix,
        'Estado' => $faker->regionAbbr,
        'Telefone1' => $faker->landline,
        'Telefone1_Ramal' => $faker->landline,
        'Telefone2' => $faker->landline,
        'Telefone2_Ramal' => $faker->landline,
        'FAX' => $faker->landline,
        'Fax_Ramal' => $faker->landline,
        'Diretor_Base' => $faker->name,
        'Pre' => rand(0, 1),
        '1_4Serie' => rand(0, 1),
        '5_8Serie' => rand(0, 1),
        'Ens_Medio' => rand(0, 1),
        'Ens_Superior' => rand(0, 1),
        'Tecnico' => rand(0, 1),
        '2_3Grau' => rand(0, 1),
        'Supletivo' => rand(0, 1),
        'Curso_Livre' => rand(0, 1),
        'Situacao' => rand(0, 5),
        'Matriz_Filial' => 0,
        'Gera_Boleto' => rand(0, 1),
        'Gera_Lista' => rand(0, 1),
        'Gera_Sindical' => rand(0, 1),
        'Sem_Cobranca' => rand(0, 1),
        'Tipo' => 'A',
        'Email' => $faker->companyEmail,
        'Email2' => $faker->email,
        'Contato' => $faker->name,
        'Contato_Nome' => $faker->name,
        'Contato_DDD' => $faker->areaCode,
        'Contato_Telefone' => $faker->landline,
        'Contato_Ramal' => $faker->landline,
        'Contato_Email' => $faker->email,
        'Correspondencia' => rand(0, 1),
        'Ok' => 2,
        'Status' => $faker->randomElement(['', 'X']),
        'Categoria' => rand(0, 1),
        'fl_listaemail' => 1,
        'nr_listadia' => 10,
        'status_web' => 2,
        'Site' => $faker->domainName,
        'CNAE' => "{$faker->randomNumber(2, true)}.{$faker->randomNumber(2, true)}-{$faker->randomDigit(1)}/00",
        'hor_1dia' => rand(0, 1),
        'hor_2dia' => rand(0, 1),
        'hor_3dia' => rand(0, 1),
        'ds_latitude' => $faker->latitude(-90, 90),
        'ds_longitude' => $faker->longitude(-180, 180),
    ];
});
